#
# Server configuration
#
server {
	listen 80;
	listen [::]:80;
  server_name nadine-votre-psy.fr www.nadine-votre-psy.fr;

  root /var/www/nadine-votre-psy.fr;
	index index.html;

  error_page 404 =302 /;

	location / {
    try_files $uri $uri.html $uri/ =404;
	}
}