#
# Server configuration
#
server {
	listen 80;
	listen [::]:80;

	root /var/www/nicoblog;
	index index.html;

	server_name _;

	location / {
    try_files $uri $uri.html $uri/ =404;
	}
}

server {
  
  server_name nicoblog.dev www.nicoblog.dev; # managed by Certbot
	root /var/www/nicoblog;
	index index.html;

  listen 443 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/nicoblog.dev/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/nicoblog.dev/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

  location / {
    # rewrite ^(.+)\.html$ $1 permanent;
		try_files $uri $uri.html $uri/ =404;
	}
}

server {
  if ($host = nicoblog.dev) {
      return 301 https://$host$request_uri;
  } # managed by Certbot

  server_name nicoblog.dev;
  listen 80;
  return 404; # managed by Certbot
}